image: php:7.4-cli

stages:
  - build
  - test

.pre:
  script:
    - pecl install xdebug
    - echo "zend_extension=/usr/lib/php/20170718/xdebug.so" >> /etc/php/7.2/cli/php.ini

composer:
  stage: build
  script:
    - composer self-update
    - composer install --no-interaction --prefer-source --dev

test:
  script:
    - vendor/bin/phpunit --coverage-text
  after_script:
    - php vendor/bin/coveralls -v

cache:
  # We key the cache using the branch's unique identifier.
  key: ${CI_COMMIT_REF_SLUG}
