image: php:7.4-cli

stages:
  - build
  - test

composer:
  stage: build
  script:
    - composer self-update
    - composer install --no-interaction --prefer-source --dev

test:
  script:
    - vendor/bin/phpunit --textdox

cache:
  # We key the cache using the branch's unique identifier.
  key: ${CI_COMMIT_REF_SLUG}
